services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: '${MYSQL_HOST}'
      MYSQL_USERNAME: '${MYSQL_USER}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    depends_on:
      - database
    networks:
      - mysql-phpmyadmin

  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./ordb.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin: